### ISSUE TITLE
Under high pressure, the reporting component can send unbounded chunks of data

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Metrics.ServiceControl#23] opened 2018-01-26 13:28 UTC
### Problem

Currently, the [RawDataReporter](https://github.com/Particular/ServiceControl.Monitoring.Data/blob/master/src/ServiceControl.Monitoring.Data/RawDataReporter.cs#L35) component accepts the minimal `flushSize` that is required to send a message to a `SC.Monitoring` instance. This value is used to provide a lower boundary for the size of flushed data and ensure that reports are sent in a reasonable batches, not keeping too much data for too long. Unfortunately, this value is used only for the lower boundary. The upper limit is set by taking [the end of the current chunk of data](https://github.com/Particular/ServiceControl.Monitoring.Data/blob/master/src/ServiceControl.Monitoring.Data/RingBuffer.cs#L74), which effectively is unbounded (or bounded by the ring itself, which is a lot).

### Proposal for a solution

I propose to introduce an upper boundary for the length of a reported chunk. This would highly likely address this problem.

### Reproduction

The following error was observed with Azure Storage Queues transport. It's worth to notice that it happens only under a big load (when number of reported values in a time of sending one reporting message is big enough).

Azure Storage Queue messages cannot exceed 64kb, this is exceeded under load.

```
2018-01-26 14:19:39,663|ERROR|99|NServiceBus.Metrics.ServiceControl.ReportingFeature+ServiceControlRawDataReporting|Error while reporting raw data to particular.monitoring.asq.
System.ArgumentException: Messages cannot be larger than 65536 bytes.
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage.GetMessageContentForTransfer(Boolean shouldEncodeMessage, QueueRequestOptions options) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Queue\CloudQueueMessage.Common.cs:line 285
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageImpl(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 2541
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.BeginAddMessage(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext, AsyncCallback callback, Object state) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1324
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.TaskFromVoidApm[T1,T2,T3,T4,T5](Func`8 beginMethod, Action`1 endMethod, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, CancellationToken cancellationToken) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 246
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1400
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1382
   at NServiceBus.AzureStorageQueues.Dispatcher.Send(MessageWrapper wrapper, CloudQueue sendQueue) in C:\BuildAgent\work\956312761da410d2\src\Transport\Dispatcher.cs:line 105
   at NServiceBus.AzureStorageQueues.Dispatcher.<Send>d__2.MoveNext() in C:\BuildAgent\work\956312761da410d2\src\Transport\Dispatcher.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Metrics.ServiceControl.ReportingFeature.ServiceControlRawDataReporting.<>c__DisplayClass3_0.<<CreateReporter>g__Sender0>d.MoveNext() in C:\BuildAgent\work\5769f7f8f0ebec65\src\NServiceBus.Metrics.ServiceControl\ReportingFeature.cs:line 250
```

**Comment by Scooletz** [comment] 2018-01-26 19:30
Can you provide a repro for this?

**Comment by ramonsmits** [comment] 2018-01-29 07:40
* Config:
  * ASQ transport
  * ASQ `transport.BatchSize(32);`:
  * `cfg.LimitMessageProcessingConcurrencyTo(300);`
  * `cfg.EnableMetrics().SendMetricDataToServiceControl("particular.monitoring", TimeSpan.FromSeconds(1));`
* Stage 1: Seed lots of messages to a queue
* Stage 2: Process the seeded messages, and you'll get the exception

I got a throughput of about 700+ messages per second for receiving.

**Comment by ramonsmits** [comment] 2018-01-29 09:17
Body is binary and is serialized via base64 which has a 33% overhead, meaning the limit isn't 64kb but 48kb(=64/4*3).

**Comment by Scooletz** [comment] 2018-01-29 10:18
Ping @Particular/metrics-maintainers for a review of the description.
Ping @ramonsmits I rephrased the description and the title of the issue as its more general, and ASQ was only a manifestation.

**Comment by ramonsmits** [comment] 2018-01-29 11:10
@Scooletz I also got the following WARN in my log file after my test was running for 15 minutes +

```
2018-01-29 10:25:56.704 WARN  RingBufferExtensions Failed to buffer metrics data for $CriticalTime after $10 attempts.
2018-01-29 10:25:56.718 WARN  RingBufferExtensions Failed to buffer metrics data for $CriticalTime after $10 attempts.
2018-01-29 10:25:56.728 WARN  RingBufferExtensions Failed to buffer metrics data for $CriticalTime after $10 attempts.
2018-01-29 10:25:56.737 WARN  RingBufferExtensions Failed to buffer metrics data for $CriticalTime after $10 attempts.
```

Not sure but I think those dollar signs should not be there. 

Also, it is also unclear what this message means and what the result is of this condition/state.

**Comment by Scooletz** [comment] 2018-01-29 11:44
This WARNing is a result of not being able to append to the metrics buffer and retrying after 10 attempts. I think this is a separate issue.

**Comment by Scooletz** [comment] 2018-01-29 11:50
Another observation somewhat connected to the way we flush data. We could kill a few birds with one stone https://github.com/Particular/ServiceControl.Monitoring.Data/issues/10

**Comment by ppittle** [comment] 2018-06-20 22:11
Has this been fixed and released?

**Comment by Scooletz** [comment] 2018-06-21 08:10
@ppittle The reporting approach has been addressed in https://github.com/Particular/ServiceControl.Monitoring.Data/pull/11 Are you observing any issue related to this?

@ramonsmits As the author of the issue, can we close it?

**Comment by ppittle** [comment] 2018-06-21 09:07
@Scooletz Actually, after re-examining the full stack trace, by exception might be a bit different:

`at NServiceBus.Metrics.ServiceControl.ServiceControlReporting.NServiceBusMetricReport.<RunReportAsync>d__1.MoveNext()`  
(full stack trace below)

**Packages:**
```
  <package id="NServiceBus" version="6.3.4" targetFramework="net452" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureStorageQueues" version="7.5.3" targetFramework="net452" />
  <package id="NServiceBus.DataBus.AzureBlobStorage" version="1.1.0" targetFramework="net452" />
  <package id="NServiceBus.Heartbeat" version="2.0.0" targetFramework="net452" />
  <package id="NServiceBus.Log4Net" version="2.0.0" targetFramework="net452" />
  <package id="NServiceBus.Metrics" version="2.0.0" targetFramework="net452" />
  <package id="NServiceBus.Metrics.ServiceControl" version="2.0.1" targetFramework="net452" />
  <package id="NServiceBus.Newtonsoft.Json" version="1.0.0" targetFramework="net452" />
  <package id="NServiceBus.Ninject" version="6.0.0" targetFramework="net452" />
  <package id="NServiceBus.Persistence.AzureStorage" version="1.2.0" targetFramework="net452" />
```

**Description:**
Is this the same problem or is this trying to send an individual metrics message that's too big?  I am using DataBus - but doing so with a custom behavior that inspects the outgoing message and determines if the message is larger than 64kb, if so it changes the outgoing message to be a LargeMessageWrapper (custom message we implemented) with a single byte[] property that's decorated with the data bus attribute.  So it's possible my behavior is too late in the pipeline?  I'm assuming metrics is implemented as a custom behavior on the pipeline?

**Full Stack Trace:**
```
exceptionMessage:Messages cannot be larger than 65536 bytes.
exceptionType:System.ArgumentException
stacktrace:   at Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage.GetMessageContentForTransfer(Boolean shouldEncodeMessage, QueueRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageImpl(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.BeginAddMessage(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext, AsyncCallback callback, Object state)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.TaskFromVoidApm[T1,T2,T3,T4,T5](Func`8 beginMethod, Action`1 endMethod, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext)
   at NServiceBus.AzureStorageQueues.Dispatcher.Send(MessageWrapper wrapper, CloudQueue sendQueue)
   at NServiceBus.AzureStorageQueues.Dispatcher.<Send>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Metrics.ServiceControl.ServiceControlReporting.NServiceBusMetricReport.<RunReportAsync>d__1.MoveNext()
```

**Comment by Scooletz** [comment] 2018-06-21 10:56
@ppittle You're using `2.0.1` of `NServiceBus.Metrics.ServiceControl` . There's a never version `2.1.0` that includes several changes, like https://github.com/Particular/NServiceBus.Metrics.ServiceControl/pull/24 , the very same error as we see above. Can you bump up the version to `2.1.0`?

**Comment by ppittle** [comment] 2018-06-21 22:43
@Scooletz - Updated and deployed.  Will need a few hours of logs to make sure the issue is resolved.  Will update this comment following monitoring.

In the mean time - is it possible for a customer to trace an issue like this into a specific nuget release version?  I did try to trace before asking you guys, but I saw the fix for this issue in #11, which was then replaced by #24 - which had 2.0.1 in the title, so I thought I was on the nuget package which included the fix.

**Comment by Scooletz** [comment] 2018-06-22 04:52
@ppittle Thank you for the feedback. I reviewed the release notes and they lack our usual milestone assignment (which issue, goes where). Let me discuss it with others. I'll leave this issue open.

**Comment by Scooletz** [comment] 2018-06-22 09:22
We'll be fixing our release notes creation and newer version will have the milestones properly assigned. For this issue, it has been fixed in: https://github.com/Particular/NServiceBus.Metrics.ServiceControl/releases/tag/2.1.0 and in the future versions of the package.

/cc @ppittle

**Closed by Scooletz** 2018-06-22 09:22 UTC
